### ISSUE TITLE
Timeout on new patch

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#21]
After the new patch hit I've been getting timeouts.
Command:
HeroesData --description 3 --storagePath "$hotsDir" --extract all --json --outputDirectory "$extractDir" --heroWarnings --localization all

This happens for both Live and PTR, an with a fresh copy of release 2.6.1 (macOS).

Error log:

One or more errors occurred. (The operation has timed out.)   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CASCLib.CDNIndexHandler.OpenDataFile(IndexEntry entry) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CDNIndexHandler.cs:line 178
   at CASCLib.CASCHandlerBase.OpenFileOnlineInternal(IndexEntry idxInfo, MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandlerBase.cs:line 85
   at CASCLib.CASCHandler.OpenFileOnline(MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandler.cs:line 238
   at CASCLib.CASCHandlerBase.OpenFile(MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandlerBase.cs:line 75
   at CASCLib.CASCHandler.OpenFile(UInt64 hash) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandler.cs:line 193
   at HeroesData.Parser.XmlGameData.CASCGameData.LoadHeroesDataStormMod() in C:\projects\heroesdataparser\HeroesData.Parser\XmlGameData\CASCGameData.cs:line 67
   at HeroesData.Parser.XmlGameData.GameData.LoadFiles() in C:\projects\heroesdataparser\HeroesData.Parser\XmlGameData\GameData.cs:line 143
   at HeroesData.Parser.XmlGameData.GameData.Initialize() in C:\projects\heroesdataparser\HeroesData.Parser\XmlGameData\GameData.cs:line 130
   at HeroesData.Program.InitializeGameData() in C:\projects\heroesdataparser\HeroesData\Program.cs:line 485
   at HeroesData.Program.Execute() in C:\projects\heroesdataparser\HeroesData\Program.cs:line 219

**Comment by koliva8245** [comment]
No clue, probably your setup.
