### ISSUE TITLE
Exception Errors on 71134

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#31]
Got 13 of these from patch pipeline today:
"Object reference not set to an instance of an object."

```
Object reference not set to an instance of an object.   at HeroesData.Parser.UnitData.Data.AbilityTalentData.StormButtonParentLookup(XElement buttonElement, AbilityTalentBase abilityTalentBase, Action`2 methodToExecute)
   at HeroesData.Parser.UnitData.Data.AbilityTalentData.SetTooltipOverrideData(XElement cButtonElement, AbilityTalentBase abilityTalentBase) in D:\a\1\s\HeroesData.Parser\UnitData\Data\AbilityTalentData.cs:line 226
   at HeroesData.Parser.UnitData.Data.AbilityData.AddAdditionalButtonAbilities(Hero hero) in D:\a\1\s\HeroesData.Parser\UnitData\Data\AbilityData.cs:line 183
   at HeroesData.Parser.UnitData.HeroParser.ParseBaseHero() in D:\a\1\s\HeroesData.Parser\UnitData\HeroParser.cs:line 102
   at HeroesData.Program.ParseHeroes(Localization localization) in D:\a\1\s\HeroesData\Program.cs:line 614
   at HeroesData.Program.Execute() in D:\a\1\s\HeroesData\Program.cs:line 228
```

**Comment by MGatner** [comment]
This is for:
`HeroesData_self --description 3 --storage-path "$hotsPtr" --extract all --output-directory "$tmpDir" --hero-warnings --localization all --json`

**Comment by koliva8245** [comment]
Use the option `--build 99999` (or any number greater than 71148).  I forgot that the ptr build number is less than live.

**Comment by MGatner** [comment]
Yeah super annoying; I had to push a manual update through. Going to ask them about them on heroprotocol.
Trying --build 99999

**Comment by MGatner** [comment]
That's working! Thanks! I'll let you know if I run into other issues with it but it made it through the first 3 localizations
