### ISSUE TITLE
Incorrect input string error when parsing HotS 2.44.0 PTR

### ISSUE THREAD

**Issue by pastelmind** [koliva8245/HeroesDataParser#37]
* HotS version: 2.44.0.72880 (PTR)
* HDP version: 3.2.2

The console output:
```
S C:\Users\Phil\Documents\GitHub> C:\Users\Phil\Downloads\hdp-3.2.2\heroesdata.exe -s 'H:\Heroes of the Storm Public Te
st' -o . --json --exclude-awards -l kokr -l enus

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Heroes Data Parser (3.2.2)
  --https://github.com/koliva8245/HeroesDataParser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 'Heroes of the Storm' directory
Localization(s): kokr enus

Loading local CASC storage...please wait
######################################################################## 100%
Finished in 13 seconds 283 milliseconds

Hots Version Build: 2.44.0.72880

Loading xml and files...
   874 xml files loaded
Finished in 4 seconds 440 milliseconds

Loading override data...
Loaded hero-overrides.xml
Finished in 0 seconds 642 milliseconds

[kokr.stormdata]
Loading text files...
    66 text files loaded
Finished in 0 seconds 327 milliseconds

Parsing gamestrings...
 41242 / 41242 total gamestrings
 41197 successfully parsed gamestrings
Finished in 40 seconds 802 milliseconds

Parsing hero data...
    85 / 85 total heroes
    83 successfully parsed heroes
Chromie - Input string was not in a correct format.
Yrel - Input string was not in a correct format.
2 failed to parse [Check logs for details]
```

The program generated two log files. First, `Exception_FailedHeroParsed_Chromie_20190319063453283.txt`:

```
Input string was not in a correct format.   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at HeroesData.Parser.HeroData.AbilityTalentData.SetTooltipCostData(Hero hero, String elementId, AbilityTalentBase abilityTalentBase)
   at HeroesData.Parser.HeroData.AbilityData.SetAbilityData(Hero hero, XElement abilityElement) in D:\a\1\s\HeroesData.Parser\HeroData\AbilityData.cs:line 92
   at HeroesData.Parser.HeroData.HeroParser.CHeroData(Hero hero) in D:\a\1\s\HeroesData.Parser\HeroData\HeroParser.cs:line 381
   at HeroesData.Parser.HeroData.HeroParser.Parse(String cHeroId) in D:\a\1\s\HeroesData.Parser\HeroData\HeroParser.cs:line 73
   at HeroesData.ParseData.<>c__DisplayClass0_0.<ParseHeroes>b__0(String cHeroId) in D:\a\1\s\HeroesData\ParseData.cs:line 52
```

Second, `Exception_FailedHeroParsed_Yrel_20190319063453755.txt`:
```
Input string was not in a correct format.   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at HeroesData.Parser.HeroData.AbilityTalentData.SetTooltipCostData(Hero hero, String elementId, AbilityTalentBase abilityTalentBase) in D:\a\1\s\HeroesData.Parser\HeroData\AbilityTalentData.cs:line 158
   at HeroesData.Parser.HeroData.AbilityData.SetAbilityData(Hero hero, XElement abilityElement) in D:\a\1\s\HeroesData.Parser\HeroData\AbilityData.cs:line 92
   at HeroesData.Parser.HeroData.HeroParser.CHeroData(Hero hero) in D:\a\1\s\HeroesData.Parser\HeroData\HeroParser.cs:line 381
   at HeroesData.Parser.HeroData.HeroParser.Parse(String cHeroId) in D:\a\1\s\HeroesData.Parser\HeroData\HeroParser.cs:line 73
   at HeroesData.ParseData.<>c__DisplayClass0_0.<ParseHeroes>b__0(String cHeroId) in D:\a\1\s\HeroesData\ParseData.cs:line 52
```

**Comment by koliva8245** [comment]
Fixed parsing, although I still need to add in the new expanded roles for heroes. Regardless, this new version won't be released until ptr goes live next week.  As always the build can be downloaded from [Azure pipelines](https://dev.azure.com/kevinkoliva/Heroes%20of%20the%20Storm%20Projects/_build?definitionId=1) on the develop branch.
