### ISSUE TITLE
Bug: Qhira

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#45]
Qhira doesn’t seem to be parsing correctly on versions 3 or 4. I don’t have the error handy but I will add it when I do.

**Comment by MGatner** [comment]
Debug log:
```
[8/6/19 7:06:27 AM]: CASCHandlerBase: loading CDN indices...
[8/6/19 7:06:28 AM]: CDNIndexHandler.Initialize() completed in 00:00:01.5025603
[8/6/19 7:06:28 AM]: CASCHandlerBase: loaded 1450805 CDN indexes
[8/6/19 7:06:28 AM]: CASCHandlerBase: loading local indices...
[8/6/19 7:06:29 AM]: LocalIndexHandler: loaded 222713 indexes
[8/6/19 7:06:29 AM]: LocalIndexHandler.Initialize() completed in 00:00:00.2551514
[8/6/19 7:06:29 AM]: CASCHandlerBase: loaded 222713 local indexes
[8/6/19 7:06:29 AM]: CASCHandler: loading encoding data...
[8/6/19 7:06:30 AM]: new EncodingHandler() completed in 00:00:00.9837394
[8/6/19 7:06:30 AM]: CASCHandler: loaded 1316783 encoding data
[8/6/19 7:06:30 AM]: CASCHandler: loading root data...
[8/6/19 7:06:30 AM]: new RootHandler() completed in 00:00:00.7935009
[8/6/19 7:06:30 AM]: CASCHandler: loaded 1109196 root data
[8/6/19 7:06:30 AM]: new CASCHandler() completed in 00:00:03.5802284
[8/6/19 7:06:30 AM]: MNDXRootHandler: loading file names...
[8/6/19 7:07:03 AM]: MNDXRootHandler: loaded 1109196 file names
[8/6/19 7:07:06 AM]: MNDXRootHandler::SetFlags() completed in 00:00:02.6415811
[8/6/19 7:07:06 AM]: LocalIndexHandler: missing index: 32D25E9E8914DE3D3400000000000000
[8/6/19 7:07:06 AM]: Local index missing: 32D25E9E8914DE3D34542927A3DD7885
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: F0D868B02859D36C0300000000000000
[8/6/19 7:07:07 AM]: Local index missing: F0D868B02859D36C035E2D5067F7FBF5
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: 75DB450EFC1A43DF4100000000000000
[8/6/19 7:07:07 AM]: Local index missing: 75DB450EFC1A43DF41F45C6B050BCD87
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: 251084E51FB26933DD00000000000000
[8/6/19 7:07:07 AM]: Local index missing: 251084E51FB26933DD4097A28F5305FB
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: BD52E04E0BD059453400000000000000
[8/6/19 7:07:07 AM]: Local index missing: BD52E04E0BD059453461CE2C8C9D172F
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: A523A9A4A168A12DE500000000000000
[8/6/19 7:07:07 AM]: Local index missing: A523A9A4A168A12DE5710DAE8FA70667
[8/6/19 7:07:07 AM]: LocalIndexHandler: missing index: 8824B7A93A4B8346DA00000000000000
[8/6/19 7:07:07 AM]: Local index missing: 8824B7A93A4B8346DAD6F4E6F3A8073E
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: E2335EB50FDB7AB0D200000000000000
[8/6/19 7:07:08 AM]: Local index missing: E2335EB50FDB7AB0D299065CC41274CA
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: 5B657F8A344D123D0800000000000000
[8/6/19 7:07:08 AM]: Local index missing: 5B657F8A344D123D0896D13772EEB65F
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: AF6BC0BDACC886FA8F00000000000000
[8/6/19 7:07:08 AM]: Local index missing: AF6BC0BDACC886FA8F10C6AAFA11D16C
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: 84DB2C27A16D66D4DB00000000000000
[8/6/19 7:07:08 AM]: Local index missing: 84DB2C27A16D66D4DB29EF9149005ADD
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: 82C8AB32B9F188145A00000000000000
[8/6/19 7:07:08 AM]: Local index missing: 82C8AB32B9F188145A94E811F0C69B86
[8/6/19 7:07:08 AM]: LocalIndexHandler: missing index: 28A13B41055D72ECA500000000000000
[8/6/19 7:07:08 AM]: Local index missing: 28A13B41055D72ECA57C301026B91286
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: 6D6B696FB1236E128000000000000000
[8/6/19 7:07:09 AM]: Local index missing: 6D6B696FB1236E128048453DAB612291
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: A0B8200C80775C88B100000000000000
[8/6/19 7:07:09 AM]: Local index missing: A0B8200C80775C88B1F655B87EBDB6D6
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: 0379138BC1268CA66800000000000000
[8/6/19 7:07:09 AM]: Local index missing: 0379138BC1268CA6684A9C8CFA4805FD
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: FFE601D711D183A09D00000000000000
[8/6/19 7:07:09 AM]: Local index missing: FFE601D711D183A09D22E6DF947BC26E
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: 392295C30D5873F0B100000000000000
[8/6/19 7:07:09 AM]: Local index missing: 392295C30D5873F0B13A50BAC2636E77
[8/6/19 7:07:09 AM]: LocalIndexHandler: missing index: 636E6D4EFC56E7630C00000000000000
[8/6/19 7:07:09 AM]: Local index missing: 636E6D4EFC56E7630C0224840B9947CA
[8/6/19 7:07:10 AM]: LocalIndexHandler: missing index: 296AE94431DD038C8E00000000000000
[8/6/19 7:07:10 AM]: Local index missing: 296AE94431DD038C8EB9455DF2357165
[8/6/19 7:07:10 AM]: LocalIndexHandler: missing index: DDF7F6FB0F08BDBE2A00000000000000
[8/6/19 7:07:10 AM]: Local index missing: DDF7F6FB0F08BDBE2A1CA70E10CC7DD0
[8/6/19 7:07:10 AM]: LocalIndexHandler: missing index: 441815CB8125FD901000000000000000
[8/6/19 7:07:10 AM]: Local index missing: 441815CB8125FD90100B9EEE0B4D2D03
[8/6/19 7:07:10 AM]: LocalIndexHandler: missing index: BB1D3ED241E4E22D1900000000000000
[8/6/19 7:07:10 AM]: Local index missing: BB1D3ED241E4E22D19BCFD3899C65576
[8/6/19 7:07:10 AM]: LocalIndexHandler: missing index: E1EDE4CC1A31EB1BB200000000000000
[8/6/19 7:07:10 AM]: Local index missing: E1EDE4CC1A31EB1BB26A7B71926B828F
[8/6/19 7:07:11 AM]: LocalIndexHandler: missing index: 02C7444EFD53AAC32400000000000000
[8/6/19 7:07:11 AM]: Local index missing: 02C7444EFD53AAC324363D5F775BD5BA
[8/6/19 7:07:11 AM]: LocalIndexHandler: missing index: 0103EAFAF12863C8DA00000000000000
[8/6/19 7:07:11 AM]: Local index missing: 0103EAFAF12863C8DAF9F0B0B4AB1F05
[8/6/19 7:07:11 AM]: LocalIndexHandler: missing index: 8AA5EE81C3C7447C0200000000000000
[8/6/19 7:07:11 AM]: Local index missing: 8AA5EE81C3C7447C02238324323724B7
[8/6/19 7:07:11 AM]: LocalIndexHandler: missing index: 902864642B149C775300000000000000
[8/6/19 7:07:11 AM]: Local index missing: 902864642B149C77532DA9638F322E7F
[8/6/19 7:07:11 AM]: LocalIndexHandler: missing index: F78B3F18D73D9E0D3200000000000000
[8/6/19 7:07:11 AM]: Local index missing: F78B3F18D73D9E0D3277BAA25D661C65
[8/6/19 7:07:12 AM]: LocalIndexHandler: missing index: 03B310D551455424D500000000000000
[8/6/19 7:07:12 AM]: Local index missing: 03B310D551455424D5D352D0624C5F61
[8/6/19 7:07:12 AM]: LocalIndexHandler: missing index: 921BA169B7D341E10E00000000000000
[8/6/19 7:07:12 AM]: Local index missing: 921BA169B7D341E10EDEAC3058B1CC6B
[8/6/19 7:07:12 AM]: LocalIndexHandler: missing index: 24517D35E29AF62E9E00000000000000
[8/6/19 7:07:12 AM]: Local index missing: 24517D35E29AF62E9E71632A5AE4360C
[8/6/19 7:07:12 AM]: LocalIndexHandler: missing index: 9329DE69331EFEABC200000000000000
[8/6/19 7:07:12 AM]: Local index missing: 9329DE69331EFEABC27BAC7DD61F8773
[8/6/19 7:07:12 AM]: LocalIndexHandler: missing index: 14598B16229AD57DEB00000000000000
[8/6/19 7:07:12 AM]: Local index missing: 14598B16229AD57DEBA458585BEFE479
[8/6/19 7:07:13 AM]: LocalIndexHandler: missing index: E7C6D2D26C74AAC61D00000000000000
[8/6/19 7:07:13 AM]: Local index missing: E7C6D2D26C74AAC61D345FC61D998904
[8/6/19 7:07:13 AM]: LocalIndexHandler: missing index: 094FD3F161BEF2343700000000000000
[8/6/19 7:07:13 AM]: Local index missing: 094FD3F161BEF2343727027E6FEF6C3E
[8/6/19 7:07:13 AM]: LocalIndexHandler: missing index: 761616ABA0EF53B66E00000000000000
[8/6/19 7:07:13 AM]: Local index missing: 761616ABA0EF53B66E85048D9C3E9DE5
[8/6/19 7:07:14 AM]: LocalIndexHandler: missing index: 4356A5EE2A71719EB600000000000000
[8/6/19 7:07:14 AM]: Local index missing: 4356A5EE2A71719EB6DE05019F67D50E
[8/6/19 7:07:15 AM]: LocalIndexHandler: missing index: 047E31B26E7C33CA3900000000000000
[8/6/19 7:07:15 AM]: Local index missing: 047E31B26E7C33CA39A16A9328225BDB
[8/6/19 7:07:15 AM]: LocalIndexHandler: missing index: 8B4AA893094CB4997F00000000000000
[8/6/19 7:07:15 AM]: Local index missing: 8B4AA893094CB4997F1D077CEBFDE81E
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: 2D4E64CC87159B7C2E00000000000000
[8/6/19 7:07:16 AM]: Local index missing: 2D4E64CC87159B7C2E2389D7D5FA467D
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: 55E4FC7F4906B590B500000000000000
[8/6/19 7:07:16 AM]: Local index missing: 55E4FC7F4906B590B5A71726378F47C2
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: C2354A97E51283B42800000000000000
[8/6/19 7:07:16 AM]: Local index missing: C2354A97E51283B4285912B9E4057E43
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: CE30B394E52A8B195500000000000000
[8/6/19 7:07:16 AM]: Local index missing: CE30B394E52A8B1955C647454A6212B1
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: 1F7FF2D1D069898F3A00000000000000
[8/6/19 7:07:16 AM]: Local index missing: 1F7FF2D1D069898F3ADC9A333A0D4263
[8/6/19 7:07:16 AM]: LocalIndexHandler: missing index: 6BB136887561948FAD00000000000000
[8/6/19 7:07:16 AM]: Local index missing: 6BB136887561948FAD03FBB4F22AF6BC
```

**Comment by MGatner** [comment]
Version 3 error log:
```
Input string was not in a correct format.   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at HeroesData.Parser.HeroData.HeroParser.CUnitData(Hero hero, XElement unitElement)
   at HeroesData.Parser.HeroData.HeroParser.Parse(String cHeroId) in D:\a\1\s\HeroesData.Parser\HeroData\HeroParser.cs:line 75
   at HeroesData.ParseData.<>c__DisplayClass0_0.<ParseHeroes>b__0(String cHeroId) in D:\a\1\s\HeroesData\ParseData.cs:line 52
```

**Comment by MGatner** [comment]
Version 4 debug log is pretty much the same. **VerificationCheck** has the following message: `[NexusHunter] has more than 1 E ability`

**Comment by MGatner** [comment]
Also:
`File not found: storm_ui_ingame_partyframe_nexushunter.dds`

**Comment by koliva8245** [comment]
Version 3 is no longer supported.

`[NexusHunter] has more than 1 E ability` has been fixed via commit https://github.com/koliva8245/HeroesDataParser/commit/a167aee3ba1e66d7fa4d76e8fcbefa10fe330522.  The extra ability should be a subability.

`File not found: storm_ui_ingame_partyframe_nexushunter.dds` is not a problem, it should be ignored.
