### ISSUE TITLE
Errors on PTR patch 2.48.0.76268

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#55]
The extract script is actually crashing. Looks like most relevant line is:
`The '"' character, hexadecimal value 0x22, cannot be included in a name.`

Script output:
```System.AggregateException: One or more errors occurred. (The '"' character, hexadecimal value 0x22, cannot be included in a name.) (The '"' character, hexadecimal value 0x22, cannot be included in a name.) ---> System.Xml.XmlException: The '"' character, hexadecimal value 0x22, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at HeroesData.Parser.GameStrings.GameStringParser.<>c__DisplayClass20_1.<ReadXmlGameData>b__5(XAttribute x) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 484
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at HeroesData.Parser.GameStrings.GameStringParser.ReadXmlGameData(List`1 parts, XAttribute parent) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 484
   at HeroesData.Parser.GameStrings.GameStringParser.ReadData(List`1 parts, List`1 scalingParts, Nullable`1& scaling) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 383
   at HeroesData.Parser.GameStrings.GameStringParser.GetValueFromPath(String pathLookup, Nullable`1& scaling) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 372
   at HeroesData.Parser.GameStrings.GameStringParser.ParseValues(ReadOnlyMemory`1 pathLookup) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 332
   at HeroesData.Parser.GameStrings.GameStringParser.ParseGameString(String tooltip, String splitter, Boolean nestedTooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 153
   at HeroesData.Parser.GameStrings.GameStringParser.ParseTooltip(String tooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 112
   at HeroesData.Parser.GameStrings.GameStringParser.TryParseRawTooltip(String key, String tooltip, String& parsedTooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 67
   at HeroesData.App.<>c__DisplayClass94_0.<ParseGameStrings>b__0(String gamestringId) in D:\a\1\s\HeroesData\App.cs:line 341
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at HeroesData.App.ParseGameStrings(Localization localization) in D:\a\1\s\HeroesData\App.cs:line 380
   at HeroesData.App.Run() in D:\a\1\s\HeroesData\App.cs:line 135
---> (Inner Exception #0) System.Xml.XmlException: The '"' character, hexadecimal value 0x22, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at HeroesData.Parser.GameStrings.GameStringParser.<>c__DisplayClass20_1.<ReadXmlGameData>b__5(XAttribute x) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 484
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at HeroesData.Parser.GameStrings.GameStringParser.ReadXmlGameData(List`1 parts, XAttribute parent) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 484
   at HeroesData.Parser.GameStrings.GameStringParser.ReadData(List`1 parts, List`1 scalingParts, Nullable`1& scaling) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 383
   at HeroesData.Parser.GameStrings.GameStringParser.GetValueFromPath(String pathLookup, Nullable`1& scaling) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 372
   at HeroesData.Parser.GameStrings.GameStringParser.ParseValues(ReadOnlyMemory`1 pathLookup) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 332
   at HeroesData.Parser.GameStrings.GameStringParser.ParseGameString(String tooltip, String splitter, Boolean nestedTooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 153
   at HeroesData.Parser.GameStrings.GameStringParser.ParseTooltip(String tooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 112
   at HeroesData.Parser.GameStrings.GameStringParser.TryParseRawTooltip(String key, String tooltip, String& parsedTooltip) in D:\a\1\s\HeroesData.Parser\GameStringParser.cs:line 67
   at HeroesData.App.<>c__DisplayClass94_0.<ParseGameStrings>b__0(String gamestringId) in D:\a\1\s\HeroesData\App.cs:line 341
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by koliva8245** [comment]
Fixed, next release won't go out until patch is live.

**Comment by pastelmind** [comment]
Is it possible to obtain atifacts for a "prerelease" or "nightly" build? My app relies on HeroesDataParser to extract all in-game tooltips *including* PTR data.

**Comment by koliva8245** [comment]
Yes, you can always obtain artifacts after every commit from the build server https://dev.azure.com/kevinkoliva/Heroes%20of%20the%20Storm%20Projects/_build/results?buildId=685

**Comment by MGatner** [comment]
Any updates on this? Artifact version is hanging for me against today's live patch. No errors but stuck at `[esmx.stormdata]`. I will give it a bit and retry.

**Comment by MGatner** [comment]
Re-ran, choked on `[dede.stormdata]` this time with the following:
```
The operation has timed out.   at System.Net.HttpWebRequest.GetResponse()
   at CASCLib.CDNIndexHandler.OpenDataFile(IndexEntry entry) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CDNIndexHandler.cs:line 170
   at CASCLib.CASCHandlerBase.OpenFileOnlineInternal(IndexEntry idxInfo, MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandlerBase.cs:line 87
   at CASCLib.CASCHandler.OpenFileOnline(MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandler.cs:line 239
   at CASCLib.CASCHandlerBase.OpenFile(MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandlerBase.cs:line 76
   at CASCLib.CASCHandler.OpenFile(UInt64 hash) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandler.cs:line 193
   at HeroesData.Loader.XmlGameData.CASCGameData.LoadHeroesDataStormMod() in D:\a\1\s\HeroesData.Loader\XmlGameData\CASCGameData.cs:line 158
   at HeroesData.Loader.XmlGameData.GameData.LoadFiles() in D:\a\1\s\HeroesData.Loader\XmlGameData\GameData.cs:line 812
   at HeroesData.Loader.XmlGameData.GameData.Load() in D:\a\1\s\HeroesData.Loader\XmlGameData\GameData.cs:line 790
   at HeroesData.App.LoadGameStrings(Localization localization) in D:\a\1\s\HeroesData\App.cs:line 553
   at HeroesData.App.Run() in D:\a\1\s\HeroesData\App.cs:line 132
```

**Comment by koliva8245** [comment]
Its fine, be sure start the game after the update to download all the (localized) game data.
